### ISSUE TITLE
Build Failure on OSX

### ISSUE THREAD

**Issue by frmsaul** [PAIR-code/facets#107] opened 2018-02-14 21:45 UTC
Hello, 

Im having an issue trying to build the demo on OSX (`Darwin LT5595 16.7.0 Darwin Kernel Version 16.7.0`)

When running the command: 
`bazel run //facets_dive/demo`

I get the output:

```
ERROR: /Users/saul.fuhrmann/FacetsTest/facets/WORKSPACE:17:1: Traceback (most recent call last):
	File "/Users/saul.fuhrmann/FacetsTest/facets/WORKSPACE", line 17
		closure_repositories()
	File "/private/var/tmp/_bazel_saul.fuhrmann/64e17fd1086fe39cfd460d5fa053149c/external/io_bazel_rules_closure/closure/repositories.bzl", line 69, in closure_repositories
		_check_bazel_version("Closure Rules", "0.4.5")
	File "/private/var/tmp/_bazel_saul.fuhrmann/64e17fd1086fe39cfd460d5fa053149c/external/io_bazel_rules_closure/closure/repositories.bzl", line 172, in _check_bazel_version
		fail(("%s requires Bazel >=%s but was...)))
Closure Rules requires Bazel >=0.4.5 but was 0.10.0-homebrew
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'third_party/workspace.bzl': no such package '@org_tensorflow_tensorboard//third_party': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'third_party/workspace.bzl': no such package '@org_tensorflow_tensorboard//third_party': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.104s
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
```

It seems that `_check_bazel_version("Closure Rules", "0.4.5")` is causing the error. 
Has anyone encountered this issue before? What would be the best way to resolve it?

Thanks,

Saul

**Comment by jimbojw** [comment] 2018-02-14 22:10
Hi frmsaul,

It looks like the version of bazel that Homebrew knows how to install may be too old. The first thing to try is to upgrade it.

```sh
$ brew upgrade bazel
```

If that doesn't work, you might have to uninstall the brew-installed version, then install bazel directly from the binary release. Instructions are here:

https://docs.bazel.build/versions/master/install-os-x.html#installing-using-binary-installer

Hope this helps!

**Comment by frmsaul** [comment] 2018-02-14 22:53
Hi Jim!

Thanks for the extremely quick reply!
I tried installing using the binary, but I am still getting a similar error, the only difference is that:
`Closure Rules requires Bazel >=0.4.5 but was 0.10.0-homebrew`
is now:
`Closure Rules requires Bazel >=0.4.5 but was 0.10.0`

It seems like `0.10.0` is the latest version bazel.

**Comment by jimbojw** [comment] 2018-02-14 23:10
OK, then I think you should install bazel directly rather than going through homebrew, unfortunately.

**Comment by frmsaul** [comment] 2018-02-14 23:41
That's what I did. It still failed.

**Comment by jimbojw** [comment] 2018-02-14 23:52
Oh, I see, sorry. Looks like the homebrew version was up-to-date after all.

Digging deeper, it looks like it's a problem with bazel's version check: https://github.com/bazelbuild/bazel/issues/4580

I'm not sure what we need to do to fix this the right way, but apparently you can replace the versions numbers in the checks with the latest verision 0.10.0 as a workaround.

**Comment by jimbojw** [comment] 2018-02-14 23:57
Root cause, looking for advice from the folks there: https://github.com/bazelbuild/bazel/issues/4425

**Comment by manuelmartinortiz** [comment] 2018-02-15 10:17
I had the same issue and I found [this comment](https://github.com/tensorflow/tensorflow/issues/16654#issuecomment-362643794)

I replaced `check_version("0.4.5")` with `check_version("0.10.0")`. The path to your file depends of your computer. Just find the file `repositories.bzl` on `$HOME/.cache/bazel`

However, I am still trying to compile an HTML to used in my own server

**Comment by jimbojw** [comment] 2018-02-27 16:46
Update: Apparently we need to update the `sha256` property of the `io_bazel_rules_closure` in line 5 of the [`WORKSPACE` file](https://github.com/PAIR-code/facets/blob/a8cfbf8d5d79785a0931936f09beb7355b32426f/WORKSPACE#L5).

Now we just need to figure out what the updated `sha256` should be.

**Comment by jameswex** [comment] 2018-03-01 19:38
I have a potential fix for this on branch build_fix, just need to test it. Once it is merged to master we can close this issue.

**Comment by jameswex** [comment] 2018-04-12 17:29
Build is back to being functional and the facets-dist html has been updated at HEAD. Sorry for the inconvenience! Please reopen if you have issues at HEAD after resyncing.

**Closed by jameswex** 2018-04-12 17:29 UTC
