### ISSUE TITLE
Is Facets compatible with Jupyter Lab?

### ISSUE THREAD

**Issue by tszumowski** [PAIR-code/facets#122] opened 2018-04-18 13:16 UTC
I tried running facets-dive in jupyter lab this morning and the HTML content didn't render. I restarted jupyter with notebook and it appeared to work. Just wondering if that's expected behavior?

**Comment by jameswex** [comment] 2018-04-18 13:31
duplicate of #113 I'll look at this in the next few days, thanks.

**Closed by jameswex** 2018-04-18 13:31 UTC
